Signup 2: https://youtu.be/hvB9uXwvg80?list=PLE5Mq0Nw_Flr1kMDtWmQYmAfURQpH3r8H

The try()catch() cant catch async error. 
 - so, in every handling async code, we need to handle the error.
 - solution\\ handle it with promise or callback. 
    - try()catch() will not be usefull without cb or promise.

in signup => send data => so its post method.

-- راجع المجلدات التالية
   1) models
   2) controllers
   3) routes 

continue in body parser.